export default [
  {
    src: `${process.env.PUBLIC_URL}/img/for_store/catalog/1.jpg`,
    title: ' Calle Cuyo, Olivos',
    price: '1000 U$D',
    description: 'PH 3 ambientes',
    colors: ['#00b3c6', '#50e3c2', '#fa4a86'],
    new: true,
  },
  {
    src: `${process.env.PUBLIC_URL}/img/for_store/catalog/2.jpg`,
    title: 'Ceballo 23, CABA',
    price: '1200 U$D',
    description: 'Departamento 3 ambientes',
    colors: ['#d4d4d4', '#5ff4d3', '#f7a9c4'],
    new: false,
  },
  {
    src: `${process.env.PUBLIC_URL}/img/for_store/catalog/3.jpg`,
    title: 'Niceto Vega, 2001',
    price: '800 U$D',
    description: 'Departamento 3 ambientes con cochera',
    colors: ['#fa93bd'],
    sale: true,
    oldPrice: '900 U$D',
  },
  {
    src: `${process.env.PUBLIC_URL}/img/for_store/catalog/4.jpg`,
    title: 'Ciudad de la Paz 1800',
    price: '1300 U$D',
    description: 'Departamento con pileta y cancha de tennis',
    colors: ['#c6890a', '#faee5a'],
  },
  {
    src: `${process.env.PUBLIC_URL}/img/for_store/catalog/5.jpg`,
    title: 'Thomas LeBreton 1039',
    price: '925 U$D',
    description: 'PH con cochera',
    colors: ['#fa93bd'],
    sale: true,
  },
  {
    src: `${process.env.PUBLIC_URL}/img/for_store/catalog/6.jpg`,
    title: 'Machain 2337',
    price: '830 U$D',
    description: 'Fondo de comercio muebleria',
    colors: ['#c6890a', '#faee5a'],
  },
  {
    src: `${process.env.PUBLIC_URL}/img/for_store/catalog/7.jpg`,
    title: 'Moldes 3023',
    price: '1000 U$D',
    description: 'Departamento 2 ambientes',
    colors: ['#00b3c6', '#50e3c2', '#fa4a86'],
    new: true,
  },
  {
    src: `${process.env.PUBLIC_URL}/img/for_store/catalog/8.jpg`,
    title: 'Lugones 1700',
    price: '750 U$D',
    description: 'PH reformado',
    colors: ['#d4d4d4', '#5ff4d3', '#f7a9c4'],
  },
];
